"""Adding_indexes

Revision ID: 18180c5375f6
Revises: 5dd9b46e659f
Create Date: 2026-03-15 22:54:15.700257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18180c5375f6'
down_revision: Union[str, Sequence[str], None] = '5dd9b46e659f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_doctor_id'), 'users', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_doctor_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    # ### end Alembic commands ###
