"""remove_test

Revision ID: 2dc5d45851f4
Revises: 829825d388fa
Create Date: 2026-03-16 00:26:34.485311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2dc5d45851f4'
down_revision: Union[str, Sequence[str], None] = '829825d388fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_column', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
