"""initial schema

Revision ID: 34ab31314c81
Revises: 
Create Date: 2026-03-15 15:03:20.082790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34ab31314c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ux_user_exercise', table_name='user_exercise_limits')
    except Exception:
        pass
    try:
        op.drop_constraint('fk_uel_user', 'user_exercise_limits', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'user_exercise_limits', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('patient', 'doctor', name='userrole'),
               existing_nullable=False)
    op.alter_column('users', 'gender',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Enum('male', 'female', 'other', name='gender'),
               existing_nullable=True)
    op.alter_column('users', 'height_cm',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'bmi',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'mobility_level',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('beginner', 'intermediate', 'advanced', name='mobilitylevel'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobility_level',
               existing_type=sa.Enum('beginner', 'intermediate', 'advanced', name='mobilitylevel'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'bmi',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('users', 'height_cm',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('male', 'female', 'other', name='gender'),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('patient', 'doctor', name='userrole'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'user_exercise_limits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_uel_user'), 'user_exercise_limits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ux_user_exercise'), 'user_exercise_limits', ['user_id', 'exercise_type'], unique=True)
    # ### end Alembic commands ###
