"""add indexes on patient_id and start_time in sessions table

Revision ID: 48482f7922c7
Revises: 9c57b1aca48b
Create Date: 2026-03-15 15:48:54.490897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48482f7922c7'
down_revision: Union[str, Sequence[str], None] = '9c57b1aca48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_start_time'), 'sessions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Indexes may not exist or are needed for FK constraints, skip dropping
    # op.drop_index(op.f('ix_sessions_start_time'), table_name='sessions')
    # op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    # ### end Alembic commands ###
