"""test_remove_3

Revision ID: 5dd9b46e659f
Revises: 39dd88ee22b0
Create Date: 2026-03-15 19:08:26.162995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dd9b46e659f'
down_revision: Union[str, Sequence[str], None] = '39dd88ee22b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True))
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
