"""test_add_4

Revision ID: 87d26bafb5c0
Revises: 2dc5d45851f4
Create Date: 2026-03-20 17:53:39.028933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d26bafb5c0'
down_revision: Union[str, Sequence[str], None] = '2dc5d45851f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_column', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_column')
    # ### end Alembic commands ###
